@@grammar::ATOM

start = {statement}+ $ ;

statement = assignment ;

assignment
  =
  {WHITESPACE} identifier {WHITESPACE} '=' {WHITESPACE} VALUE ';'
  ;
identifier = LETTER {ALPHANUM} ;

VALUE = TRUE | FALSE | INT | FLOAT | STRING ;
TRUE = 'true';
FALSE = 'false';
INT = ['+' | '-'] {DIGIT}+ ;
FLOAT
  = 
  | ['+' | '-'] {DIGIT}+ '.' {DIGIT}
  | ['+' | '-'] '.' {DIGIT}+
  ;
STRING
  =
  | '"' { /[^\\\r\n\f"]/ | '\\"' } '"'
  | "'" { /[^\\\r\n\f']/ | "\\'" } "'"
  ;

ZERO = '0' ;
ONE = '1' ;
NONZERO_DIGIT = /[1-9]/ ;
DIGIT = /[0-9]/ ;
UPPERCASE_LETTER = /[A-Z]/ ;
LOWERCASE_LETTER = /[a-z]/ ;
LETTER = UPPERCASE_LETTER | LOWERCASE_LETTER ;
ALPHANUM = DIGIT | LETTER ;
WHITESPACE = /\s+/ ;
NEWLINE = (WHITESPACE | (['\\r'] /[\n\r\f]/) [WHITESPACE]) ;
